name: Audio_Enhancement_CNN
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - jupyter
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - pyyaml
  - pip:
      - librosa
      - pesq
      - pystoi
      - soundfile
      - soxr
      - torch
      - torchaudio
      - tqdm
      - tensorboard
      - huggingface-hub
      - pyarrow
