name: Audio_Enhancement_CNN
channels:
  - defaults
dependencies:
  - appnope=0.1.4=py310hca03da5_0
  - argon2-cffi=25.1.0=py310hca03da5_0
  - argon2-cffi-bindings=25.1.0=py310h254cc4a_0
  - asttokens=3.0.0=py310hca03da5_0
  - async-lru=2.0.5=py310hca03da5_0
  - attrs=25.4.0=py310hca03da5_2
  - babel=2.17.0=py310hca03da5_0
  - beautifulsoup4=4.14.3=py310hca03da5_0
  - bleach=6.3.0=py310hca03da5_0
  - brotlicffi=1.2.0.0=py310h50f4ffc_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - certifi=2026.01.04=py310hca03da5_0
  - cffi=2.0.0=py310h73c2a22_1
  - charset-normalizer=3.4.4=py310hca03da5_0
  - comm=0.2.3=py310hca03da5_0
  - debugpy=1.8.16=py310h50f4ffc_1
  - decorator=5.2.1=py310hca03da5_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=2.2.1=py310hca03da5_0
  - expat=2.7.4=h50f4ffc_0
  - h11=0.16.0=py310hca03da5_1
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py310hca03da5_0
  - httpx=0.28.1=py310hca03da5_1
  - idna=3.11=py310hca03da5_0
  - ipykernel=6.31.0=py310h7eb115d_0
  - ipython=8.30.0=py310hca03da5_0
  - ipython_pygments_lexers=1.1.1=py310hca03da5_0
  - ipywidgets=8.1.7=py310hca03da5_1
  - jedi=0.19.2=py310hca03da5_0
  - jinja2=3.1.6=py310hca03da5_0
  - json5=0.12.1=py310hca03da5_0
  - jsonschema=4.25.1=py310hca03da5_0
  - jsonschema-specifications=2025.9.1=py310hca03da5_0
  - jupyter=1.1.1=py310hca03da5_0
  - jupyter-lsp=2.3.0=py310hca03da5_0
  - jupyter_client=8.8.0=py310hca03da5_0
  - jupyter_console=6.6.3=py310hca03da5_0
  - jupyter_core=5.9.1=py310hca03da5_0
  - jupyter_events=0.12.0=py310hca03da5_1
  - jupyter_server=2.17.0=py310hca03da5_1
  - jupyter_server_terminals=0.5.4=py310hca03da5_0
  - jupyterlab=4.5.3=py310hca03da5_1
  - jupyterlab_pygments=0.3.0=py310hca03da5_0
  - jupyterlab_server=2.28.0=py310hca03da5_1
  - jupyterlab_widgets=3.0.16=py310hca03da5_1
  - libcxx=21.1.8=hb4ce287_0
  - libexpat=2.7.4=h50f4ffc_0
  - libffi=3.4.4=hca03da5_1
  - libiconv=1.18=h92f5915_0
  - libsodium=1.0.20=h897f8a9_0
  - libzlib=1.3.1=h5f15de7_0
  - matplotlib-inline=0.2.1=py310hca03da5_0
  - mistune=3.1.2=py310hca03da5_0
  - nbclient=0.10.4=py310hca03da5_0
  - nbconvert=7.16.6=py310hca03da5_0
  - nbconvert-core=7.16.6=py310hca03da5_0
  - nbconvert-pandoc=7.16.6=py310hca03da5_0
  - nbformat=5.10.4=py310hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=py310hca03da5_0
  - notebook=7.5.3=py310hca03da5_0
  - notebook-shim=0.2.4=py310hca03da5_1
  - openssl=3.0.19=ha0b305a_0
  - overrides=7.7.0=py310hca03da5_0
  - packaging=25.0=py310hca03da5_1
  - pandoc=3.8=hca03da5_0
  - pandocfilters=1.5.1=py310hca03da5_0
  - parso=0.8.5=py310hca03da5_0
  - pexpect=4.9.0=py310hca03da5_1
  - pip=26.0.1=pyhc872135_0
  - prometheus_client=0.21.1=py310hca03da5_0
  - prompt-toolkit=3.0.52=py310hca03da5_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py310haa24f5a_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py310hca03da5_0
  - pygments=2.19.2=py310hca03da5_0
  - pysocks=1.7.1=py310hca03da5_1
  - python=3.10.19=hf701271_0
  - python-dateutil=2.9.0post0=py310hca03da5_2
  - python-fastjsonschema=2.21.2=py310hca03da5_0
  - python-json-logger=4.0.0=py310hca03da5_0
  - pyyaml=6.0.3=py310h091b9d3_0
  - pyzmq=27.1.0=py310h5a8c52c_1
  - qtconsole=5.7.1=py310hca03da5_0
  - qtpy=2.4.3=py310hca03da5_0
  - readline=8.3=h0b18652_0
  - referencing=0.37.0=py310hca03da5_0
  - requests=2.32.5=py310hca03da5_1
  - rfc3339-validator=0.1.4=py310hca03da5_0
  - rfc3986-validator=0.1.1=py310hca03da5_0
  - rpds-py=0.28.0=py310h931abed_0
  - send2trash=1.8.3=py310hca03da5_0
  - setuptools=80.10.2=py310hca03da5_0
  - six=1.17.0=py310hca03da5_0
  - sniffio=1.3.1=py310hca03da5_0
  - soupsieve=2.5=py310hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - stack_data=0.6.3=py310hca03da5_0
  - terminado=0.18.1=py310hca03da5_1
  - tinycss2=1.4.0=py310hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - tomli=2.4.0=py310hca03da5_0
  - tornado=6.5.4=py310haa24f5a_0
  - traitlets=5.14.3=py310hca03da5_0
  - typing-extensions=4.15.0=py310hca03da5_0
  - typing_extensions=4.15.0=py310hca03da5_0
  - urllib3=2.6.3=py310hca03da5_0
  - wcwidth=0.2.14=py310hca03da5_0
  - webencodings=0.5.1=py310hca03da5_1
  - websocket-client=1.8.0=py310hca03da5_0
  - wheel=0.46.3=py310hca03da5_0
  - widgetsnbextension=4.0.14=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h2c7f8f0_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - absl-py==2.4.0
      - annotated-doc==0.0.4
      - anyio==4.12.1
      - audioread==3.1.0
      - click==8.3.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - exceptiongroup==1.3.1
      - filelock==3.24.3
      - fonttools==4.61.1
      - fsspec==2026.2.0
      - grpcio==1.78.1
      - hf-xet==1.2.0
      - huggingface-hub==1.4.1
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.46.0
      - markdown==3.10.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.1.2
      - networkx==3.4.2
      - numba==0.64.0
      - numpy==2.2.6
      - pandas==2.3.3
      - pesq==0.0.4
      - pillow==12.1.1
      - platformdirs==4.9.2
      - pooch==1.9.0
      - protobuf==6.33.5
      - pycparser==3.0
      - pyparsing==3.3.2
      - pystoi==0.4.1
      - pytz==2025.2
      - rich==14.3.3
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - shellingham==1.5.4
      - soundfile==0.13.1
      - soxr==1.0.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - torch==2.10.0
      - torchaudio==2.10.0
      - tqdm==4.67.3
      - typer==0.24.1
      - typer-slim==0.24.0
      - tzdata==2025.3
      - werkzeug==3.1.6
